// This file is automatically generated from your CSS. Any edits will be overwritten.
export const canvas: string;
export const overlay: string;
export const modal: string;
export const closebutton: string;
